In [1]:
import tensorflow as tf
# X and Y data
x_train = [1,2,3]
y_train = [1,2,3]

# trainable variables: could be changed
W = tf.Variable(tf.random_normal([1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

# Our hypothesis XW+b
hypothesis = x_train * W + b

In [2]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - y_train))
 # reduce_mean은 평균 내주는 함수

In [3]:
# GradientDescent
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

In [6]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

# Fit the line
for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step,sess.run(cost),sess.run(W),sess.run(b))

0 2.05059 [ 0.83080244] [-1.08691406]
20 0.111419 [ 1.30399573] [-0.83117253]
40 0.0853168 [ 1.33400893] [-0.77262294]
60 0.0773422 [ 1.32252979] [-0.7344569]
80 0.0702421 [ 1.30777371] [-0.69976336]
100 0.063795 [ 1.29334795] [-0.66686022]
120 0.0579396 [ 1.27956522] [-0.63551867]
140 0.0526217 [ 1.26642692] [-0.60565138]
160 0.0477919 [ 1.25390589] [-0.57718784]
180 0.0434053 [ 1.24197328] [-0.55006212]
200 0.0394214 [ 1.23060143] [-0.52421129]
220 0.0358031 [ 1.21976399] [-0.4995752]
240 0.032517 [ 1.20943582] [-0.47609699]
260 0.0295325 [ 1.19959319] [-0.45372218]
280 0.0268218 [ 1.19021297] [-0.43239886]
300 0.02436 [ 1.18127358] [-0.41207772]
320 0.0221242 [ 1.17275453] [-0.39271158]
340 0.0200935 [ 1.16463578] [-0.37425566]
360 0.0182493 [ 1.15689838] [-0.35666704]
380 0.0165743 [ 1.14952481] [-0.3399049]
400 0.015053 [ 1.14249766] [-0.32393068]
420 0.0136714 [ 1.13580084] [-0.30870709]
440 0.0124166 [ 1.12941873] [-0.29419908]
460 0.0112769 [ 1.12333667] [-0.28037283]
480 0.010

In [13]:
X = tf.placeholder(tf.float32, shape=[None])
Y = tf.placeholder(tf.float32, shape=[None])

# Fit the line
for step in range(2001):
    cost_val,W_val,b_val,_= sess.run([cost,W,b,train],
             feed_dict={X:[1,2,3],Y:[1,2,3]})
    if step % 20 == 0:
        print(step,cost_val,W_val,b_val)

0 6.73886e-06 [ 1.00300777] [-0.00683733]
20 6.12039e-06 [ 1.00286651] [-0.00651603]
40 5.55845e-06 [ 1.0027318] [-0.00620983]
60 5.04865e-06 [ 1.00260341] [-0.00591805]
80 4.58504e-06 [ 1.0024811] [-0.00563996]
100 4.16451e-06 [ 1.00236452] [-0.00537494]
120 3.78212e-06 [ 1.00225329] [-0.00512238]
140 3.43511e-06 [ 1.00214744] [-0.00488168]
160 3.12e-06 [ 1.00204659] [-0.00465228]
180 2.83357e-06 [ 1.00195038] [-0.00443369]
200 2.57364e-06 [ 1.00185871] [-0.00422537]
220 2.33756e-06 [ 1.00177145] [-0.00402684]
240 2.1231e-06 [ 1.00168836] [-0.00383762]
260 1.92804e-06 [ 1.00160885] [-0.00365732]
280 1.75135e-06 [ 1.00153339] [-0.0034855]
300 1.59044e-06 [ 1.00146127] [-0.00332174]
320 1.44448e-06 [ 1.00139272] [-0.00316566]
340 1.31223e-06 [ 1.00132728] [-0.00301696]
360 1.19167e-06 [ 1.00126481] [-0.00287526]
380 1.08248e-06 [ 1.00120556] [-0.00274024]
400 9.83173e-07 [ 1.00114906] [-0.00261158]
420 8.92947e-07 [ 1.00109506] [-0.00248895]
440 8.11108e-07 [ 1.00104368] [-0.00237205]
4

In [14]:
for step in range(2001):
    cost_val,W_val,b_val,_= sess.run([cost,W,b,train],
             feed_dict={X:[1,2,3,4,5],Y:[2.1,3.1,4.1,5.1,6.1]})
    if step % 20 == 0:
        print(step,cost_val,W_val,b_val)

0 4.48377e-10 [ 1.00002456] [ -5.57282474e-05]
20 4.09155e-10 [ 1.00002337] [ -5.31179685e-05]
40 3.70373e-10 [ 1.00002229] [ -5.06491524e-05]
60 3.37025e-10 [ 1.00002134] [ -4.83174190e-05]
80 3.05917e-10 [ 1.00002038] [ -4.61164163e-05]
100 2.79878e-10 [ 1.00001943] [ -4.40318436e-05]
120 2.56441e-10 [ 1.0000186] [ -4.20708493e-05]
140 2.33683e-10 [ 1.00001788] [ -4.02123806e-05]
160 2.1368e-10 [ 1.00001717] [ -3.84500745e-05]
180 1.95718e-10 [ 1.00001645] [ -3.67918728e-05]
200 1.79625e-10 [ 1.00001574] [ -3.52179050e-05]
220 1.63938e-10 [ 1.00001514] [ -3.37305682e-05]
240 1.52364e-10 [ 1.00001442] [ -3.23298555e-05]
260 1.41091e-10 [ 1.00001383] [ -3.10074283e-05]
280 1.28447e-10 [ 1.00001335] [ -2.97549304e-05]
300 1.18689e-10 [ 1.00001287] [ -2.85612477e-05]
320 1.10159e-10 [ 1.0000124] [ -2.74398863e-05]
340 1.01617e-10 [ 1.00001192] [ -2.63872698e-05]
360 9.34281e-11 [ 1.00001144] [ -2.53795570e-05]
380 8.76016e-11 [ 1.00001109] [ -2.44350231e-05]
400 8.13429e-11 [ 1.00001073]

In [18]:
# Testing our model
print(sess.run(hypothesis, feed_dict={X:[5]}))
print(sess.run(hypothesis, feed_dict={X:[2.5]}))
print(sess.run(hypothesis, feed_dict={X:[1.5,3.5]}))

[ 0.99999571  2.          3.00000429]
[ 0.99999571  2.          3.00000429]
[ 0.99999571  2.          3.00000429]
