In [3]:
import tensorflow as tf
x1_data = [73,93,89,96,73]
x2_data = [80,88,91,98,66]
x3_data = [75,93,90,100,70]
y_data = [152,185,180,196,142]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]),name='weight1')
w2 = tf.Variable(tf.random_normal([1]),name='weight2')
w3 = tf.Variable(tf.random_normal([1]),name='weight3')
b = tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [6]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph 
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train],
                                  feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  39465.2 
Prediction:
 [-22.26424789 -28.908638   -27.26270103 -30.81388092 -21.70362663]
10 Cost:  3.36993 
Prediction:
 [ 153.45910645  182.31011963  180.84829712  195.81454468  139.4055481 ]
20 Cost:  2.99338 
Prediction:
 [ 153.98425293  182.95365906  181.47596741  196.49882507  139.89884949]
30 Cost:  2.97814 
Prediction:
 [ 153.9793396   182.96009827  181.47587585  196.4994812   139.90618896]
40 Cost:  2.96299 
Prediction:
 [ 153.97280884  182.96455383  181.47386169  196.49806213  139.91203308]
50 Cost:  2.94792 
Prediction:
 [ 153.96630859  182.96902466  181.47187805  196.49665833  139.91786194]
60 Cost:  2.93295 
Prediction:
 [ 153.95982361  182.97346497  181.46987915  196.49525452  139.92366028]
70 Cost:  2.91805 
Prediction:
 [ 153.95336914  182.97790527  181.46791077  196.49383545  139.92947388]
80 Cost:  2.90324 
Prediction:
 [ 153.94689941  182.9822998   181.46591187  196.49241638  139.93522644]
90 Cost:  2.8885 
Prediction:
 [ 153.94047546  182.98672485  181.46394

840 Cost:  1.98277 
Prediction:
 [ 153.50444031  183.28543091  181.33004761  196.39625549  140.33125305]
850 Cost:  1.97301 
Prediction:
 [ 153.49919128  183.28900146  181.32844543  196.39511108  140.3359375 ]
860 Cost:  1.96331 
Prediction:
 [ 153.49398804  183.29258728  181.32684326  196.39399719  140.34062195]
870 Cost:  1.95365 
Prediction:
 [ 153.48878479  183.29615784  181.32522583  196.39285278  140.34527588]
880 Cost:  1.94403 
Prediction:
 [ 153.48358154  183.29972839  181.32363892  196.39172363  140.34992981]
890 Cost:  1.93449 
Prediction:
 [ 153.47839355  183.30326843  181.322052    196.39059448  140.35455322]
900 Cost:  1.925 
Prediction:
 [ 153.47323608  183.30679321  181.32046509  196.38948059  140.35917664]
910 Cost:  1.91553 
Prediction:
 [ 153.46807861  183.31033325  181.31887817  196.3883667   140.36380005]
920 Cost:  1.90614 
Prediction:
 [ 153.46295166  183.31385803  181.31730652  196.38726807  140.36839294]
930 Cost:  1.89678 
Prediction:
 [ 153.45780945  183.3173

1690 Cost:  1.31608 
Prediction:
 [ 153.10621643  183.55819702  181.20770264  196.31008911  140.68730164]
1700 Cost:  1.30992 
Prediction:
 [ 153.10205078  183.56105042  181.20643616  196.30918884  140.69102478]
1710 Cost:  1.3038 
Prediction:
 [ 153.09791565  183.56390381  181.20515442  196.30830383  140.69471741]
1720 Cost:  1.2977 
Prediction:
 [ 153.09376526  183.56674194  181.20387268  196.30738831  140.69841003]
1730 Cost:  1.29165 
Prediction:
 [ 153.08963013  183.56954956  181.20262146  196.30651855  140.70211792]
1740 Cost:  1.28562 
Prediction:
 [ 153.08551025  183.57237244  181.20133972  196.30561829  140.70578003]
1750 Cost:  1.27963 
Prediction:
 [ 153.08140564  183.57518005  181.20007324  196.30473328  140.70944214]
1760 Cost:  1.27367 
Prediction:
 [ 153.07731628  183.57798767  181.19882202  196.30384827  140.71310425]
1770 Cost:  1.26772 
Prediction:
 [ 153.07322693  183.58078003  181.19755554  196.30297852  140.71676636]
1780 Cost:  1.26184 
Prediction:
 [ 153.06916809

In [7]:
# 위의 경우 식이 더 복잡해질 경우 보기 힘듬... Matrix로 표현해보자

x_data = [[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = tf.matmul(X,W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis-Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph 
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost,hypothesis,train],feed_dict={X:x_data,Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  6085.6 
Prediction:
 [[  81.82956696]
 [ 101.6424942 ]
 [  98.66771698]
 [ 107.7232666 ]
 [  77.59568787]]
10 Cost:  0.699988 
Prediction:
 [[ 150.83473206]
 [ 184.58222961]
 [ 180.389328  ]
 [ 196.71575928]
 [ 140.85821533]]
20 Cost:  0.64402 
Prediction:
 [[ 151.04319763]
 [ 184.83345032]
 [ 180.63653564]
 [ 196.98471069]
 [ 141.05023193]]
30 Cost:  0.643762 
Prediction:
 [[ 151.04347229]
 [ 184.8344574 ]
 [ 180.63719177]
 [ 196.98518372]
 [ 141.0513916 ]]
40 Cost:  0.643504 
Prediction:
 [[ 151.04312134]
 [ 184.83473206]
 [ 180.63713074]
 [ 196.98483276]
 [ 141.05197144]]
50 Cost:  0.643236 
Prediction:
 [[ 151.04278564]
 [ 184.83499146]
 [ 180.6370697 ]
 [ 196.98448181]
 [ 141.05256653]]
60 Cost:  0.642977 
Prediction:
 [[ 151.04246521]
 [ 184.83526611]
 [ 180.63702393]
 [ 196.98417664]
 [ 141.05317688]]
70 Cost:  0.642715 
Prediction:
 [[ 151.04211426]
 [ 184.83551025]
 [ 180.63693237]
 [ 196.98382568]
 [ 141.05375671]]
80 Cost:  0.642449 
Prediction:
 [[ 151.04177856]
 [

980 Cost:  0.620843 
Prediction:
 [[ 151.01629639]
 [ 184.85586548]
 [ 180.63237   ]
 [ 196.95428467]
 [ 141.10266113]]
990 Cost:  0.620623 
Prediction:
 [[ 151.01605225]
 [ 184.85604858]
 [ 180.63233948]
 [ 196.95396423]
 [ 141.10314941]]
1000 Cost:  0.620403 
Prediction:
 [[ 151.01582336]
 [ 184.85624695]
 [ 180.63230896]
 [ 196.95365906]
 [ 141.1036377 ]]
1010 Cost:  0.620177 
Prediction:
 [[ 151.01559448]
 [ 184.85643005]
 [ 180.63227844]
 [ 196.95333862]
 [ 141.10412598]]
1020 Cost:  0.61997 
Prediction:
 [[ 151.01535034]
 [ 184.85661316]
 [ 180.63224792]
 [ 196.95303345]
 [ 141.104599  ]]
1030 Cost:  0.619734 
Prediction:
 [[ 151.01513672]
 [ 184.85681152]
 [ 180.63220215]
 [ 196.95272827]
 [ 141.10510254]]
1040 Cost:  0.619518 
Prediction:
 [[ 151.01489258]
 [ 184.85697937]
 [ 180.63215637]
 [ 196.95240784]
 [ 141.10557556]]
1050 Cost:  0.619296 
Prediction:
 [[ 151.0146637 ]
 [ 184.85717773]
 [ 180.63214111]
 [ 196.9520874 ]
 [ 141.10606384]]
1060 Cost:  0.619078 
Prediction:
 

1990 Cost:  0.599924 
Prediction:
 [[ 150.99694824]
 [ 184.87200928]
 [ 180.63008118]
 [ 196.92416382]
 [ 141.1479187 ]]
2000 Cost:  0.599726 
Prediction:
 [[ 150.99679565]
 [ 184.87214661]
 [ 180.63006592]
 [ 196.9238739 ]
 [ 141.14833069]]
