In [1]:
import tensorflow as tf
import numpy as np
xy = np.loadtxt('data-01-test-score.csv',delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [2]:
print(x_data.shape,x_data,len(x_data))
print(y_data.shape,y_data)

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25
(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]


In [3]:
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [6]:
# Hypothesis
hypothesis = tf.matmul(X,W) + b
# Simplified cost/los function
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [7]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the loop.
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train],
    feed_dict = {X:x_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
             "\nPrediction:\n", hy_val)

0 Cost:  42557.4 
Prediction:
 [[-39.4226532 ]
 [-48.27185059]
 [-47.08208847]
 [-51.61828613]
 [-36.74160004]
 [-27.6961441 ]
 [-38.87902069]
 [-29.13868332]
 [-45.72551346]
 [-43.1727829 ]
 [-37.37119675]
 [-37.36473846]
 [-48.31421661]
 [-39.73031235]
 [-39.22646332]
 [-49.22577286]
 [-37.6980896 ]
 [-46.67956543]
 [-45.86919785]
 [-41.00222397]
 [-45.60765839]
 [-45.55502319]
 [-43.31007767]
 [-38.97646332]
 [-49.73350143]]
10 Cost:  17.036 
Prediction:
 [[ 153.16152954]
 [ 183.20922852]
 [ 180.99295044]
 [ 196.77909851]
 [ 139.79833984]
 [ 102.47086334]
 [ 147.06103516]
 [ 108.71389008]
 [ 170.62075806]
 [ 157.23171997]
 [ 141.76966858]
 [ 139.27996826]
 [ 187.31253052]
 [ 156.13623047]
 [ 147.57089233]
 [ 185.67799377]
 [ 148.83525085]
 [ 176.46775818]
 [ 178.76425171]
 [ 159.99095154]
 [ 172.43612671]
 [ 171.61070251]
 [ 164.57460022]
 [ 155.17967224]
 [ 190.16490173]]
20 Cost:  14.9337 
Prediction:
 [[ 154.48316956]
 [ 184.80999756]
 [ 182.56335449]
 [ 198.49594116]
 [ 141.0168

470 Cost:  12.2569 
Prediction:
 [[ 154.13218689]
 [ 184.87597656]
 [ 182.35496521]
 [ 198.5375061 ]
 [ 140.9667511 ]
 [ 103.81504822]
 [ 148.64596558]
 [ 110.2497406 ]
 [ 172.63050842]
 [ 159.7459259 ]
 [ 143.16320801]
 [ 140.98013306]
 [ 188.44659424]
 [ 156.71888733]
 [ 149.26821899]
 [ 187.58537292]
 [ 149.2111969 ]
 [ 178.42781067]
 [ 179.72462463]
 [ 160.84606934]
 [ 174.26864624]
 [ 173.41090393]
 [ 166.20092773]
 [ 155.52145386]
 [ 191.68406677]]
480 Cost:  12.2081 
Prediction:
 [[ 154.12507629]
 [ 184.87693787]
 [ 182.35057068]
 [ 198.53813171]
 [ 140.96537781]
 [ 103.82350159]
 [ 148.65182495]
 [ 110.26132965]
 [ 172.64022827]
 [ 159.76774597]
 [ 143.16612244]
 [ 140.98928833]
 [ 188.43666077]
 [ 156.70352173]
 [ 149.27613831]
 [ 187.59065247]
 [ 149.19294739]
 [ 178.43606567]
 [ 179.71284485]
 [ 160.83547974]
 [ 174.27496338]
 [ 173.41648865]
 [ 166.2046051 ]
 [ 155.50172424]
 [ 191.68099976]]
490 Cost:  12.1597 
Prediction:
 [[ 154.11799622]
 [ 184.87789917]
 [ 182.34620667

900 Cost:  10.4841 
Prediction:
 [[ 153.85720825]
 [ 184.90939331]
 [ 182.18284607]
 [ 198.56391907]
 [ 140.90614319]
 [ 104.14276123]
 [ 148.88162231]
 [ 110.7155304 ]
 [ 173.00741577]
 [ 160.6002655 ]
 [ 143.27905273]
 [ 141.33692932]
 [ 188.0559845 ]
 [ 156.11247253]
 [ 149.58299255]
 [ 187.78956604]
 [ 148.48680115]
 [ 178.76152039]
 [ 179.26217651]
 [ 160.43170166]
 [ 174.52119446]
 [ 173.62780762]
 [ 166.34985352]
 [ 154.74815369]
 [ 191.56071472]]
910 Cost:  10.4499 
Prediction:
 [[ 153.85150146]
 [ 184.90997314]
 [ 182.17919922]
 [ 198.56451416]
 [ 140.90467834]
 [ 104.14955902]
 [ 148.88671875]
 [ 110.72559357]
 [ 173.01522827]
 [ 160.61819458]
 [ 143.2815094 ]
 [ 141.34437561]
 [ 188.04769897]
 [ 156.09960938]
 [ 149.58972168]
 [ 187.79380798]
 [ 148.47134399]
 [ 178.76876831]
 [ 179.25241089]
 [ 160.42298889]
 [ 174.52661133]
 [ 173.6322937 ]
 [ 166.35308838]
 [ 154.73187256]
 [ 191.55801392]]
920 Cost:  10.416 
Prediction:
 [[ 153.84584045]
 [ 184.9105835 ]
 [ 182.17562866]

 [[ 153.63258362]
 [ 184.92881775]
 [ 182.03787231]
 [ 198.58906555]
 [ 140.8417511 ]
 [ 104.41135406]
 [ 149.09133911]
 [ 111.12932587]
 [ 173.31626892]
 [ 161.31669617]
 [ 143.37937927]
 [ 141.63368225]
 [ 187.72370911]
 [ 155.59370422]
 [ 149.85713196]
 [ 187.95704651]
 [ 147.86019897]
 [ 179.06187439]
 [ 178.87171936]
 [ 160.08422852]
 [ 174.74357605]
 [ 173.80621338]
 [ 166.4851532 ]
 [ 154.09643555]
 [ 191.44911194]]
1350 Cost:  9.19186 
Prediction:
 [[ 153.62805176]
 [ 184.92912292]
 [ 182.03489685]
 [ 198.58959961]
 [ 140.84028625]
 [ 104.41679382]
 [ 149.09576416]
 [ 111.13807678]
 [ 173.32249451]
 [ 161.3313446 ]
 [ 143.38145447]
 [ 141.63970947]
 [ 187.71685791]
 [ 155.58296204]
 [ 149.86286926]
 [ 187.9604187 ]
 [ 147.84715271]
 [ 179.06826782]
 [ 178.8637085 ]
 [ 160.07711792]
 [ 174.7482605 ]
 [ 173.80981445]
 [ 166.48803711]
 [ 154.08305359]
 [ 191.44673157]]
1360 Cost:  9.16819 
Prediction:
 [[ 153.62356567]
 [ 184.92941284]
 [ 182.0319519 ]
 [ 198.59014893]
 [ 140.8388

1810 Cost:  8.2791 
Prediction:
 [[ 153.44378662]
 [ 184.93707275]
 [ 181.9115448 ]
 [ 198.61383057]
 [ 140.7723999 ]
 [ 104.63804626]
 [ 149.2852478 ]
 [ 111.51134491]
 [ 173.57678223]
 [ 161.93780518]
 [ 143.46951294]
 [ 141.88851929]
 [ 187.43093872]
 [ 155.13365173]
 [ 150.10501099]
 [ 188.09848022]
 [ 147.29776001]
 [ 179.34280396]
 [ 178.5305481 ]
 [ 159.78295898]
 [ 174.94702148]
 [ 173.95739746]
 [ 166.61288452]
 [ 153.52807617]
 [ 191.34417725]]
1820 Cost:  8.26279 
Prediction:
 [[ 153.44026184]
 [ 184.93711853]
 [ 181.90911865]
 [ 198.61431885]
 [ 140.7709198 ]
 [ 104.64228058]
 [ 149.28904724]
 [ 111.51885223]
 [ 173.58164978]
 [ 161.94961548]
 [ 143.47125244]
 [ 141.89331055]
 [ 187.42530823]
 [ 155.12477112]
 [ 150.1098175 ]
 [ 188.10110474]
 [ 147.28684998]
 [ 179.34835815]
 [ 178.52403259]
 [ 159.77722168]
 [ 174.95100403]
 [ 173.96022034]
 [ 166.61540222]
 [ 153.51722717]
 [ 191.34207153]]
1830 Cost:  8.24659 
Prediction:
 [[ 153.43678284]
 [ 184.93717957]
 [ 181.906738

In [9]:
# Ask my score
print("Your score will be ", sess.run(hypothesis,
                                     feed_dict={X:[[100,70,101]]}))
print("Other scores will be ", sess.run(hypothesis,
                                     feed_dict={X:[[60,70,110],[90,100,80]]}))


Your score will be  [[ 185.1776886]]
Other scores will be  [[ 170.79060364]
 [ 179.01274109]]
